# Generated by Django 5.2.17 on 2026-09-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('unit', models.CharField(choices=[('kg', 'Kg'), ('l', 'Litro'), ('un', 'Unidade')], max_length=2)),
                ('target_stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_consumption', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expiration_date', models.DateField()),
                ('ran_during_period', models.BooleanField(default=True)),
            ],
        ),
    ]
